{
 "title": "Blue Iris",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  unix_timestamp(created) AS \"time\",\r\n  cast(StatNBR as decimal(18,2)) as 'CPU'\r\nFROM DeviceMonitoring\r\nWHERE\r\n  $__timeFilter(created)\r\n  and\r\n  DeviceNM='Blue Iris'\r\n  and\r\n  StatNM='CPU'\r\nORDER BY created"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  unix_timestamp(created) AS \"time\",\r\n  cast(StatNBR as decimal(18,2)) as 'Percent Used'\r\nFROM DeviceMonitoring\r\nWHERE\r\n  $__timeFilter(created)\r\n  and\r\n  DeviceNM='Blue Iris'\r\n  and\r\n  StatNM='RAM'\r\nORDER BY created"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  unix_timestamp(created) AS \"time\",\r\n  cast(StatNBR as decimal(18,2)) as 'GPU'\r\nFROM DeviceMonitoring\r\nWHERE\r\n  $__timeFilter(created)\r\n  and\r\n  DeviceNM='Blue Iris'\r\n  and\r\n  StatNM='GPU'\r\nORDER BY created"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  unix_timestamp(created) AS \"time\",\r\n  cast(StatNBR as decimal(18,2)) as 'Disk Used'\r\nFROM DeviceMonitoring\r\nWHERE\r\n  $__timeFilter(created)\r\n  and\r\n  DeviceNM='Blue Iris'\r\n  and\r\n  StatNM='Disk'\r\nORDER BY created"
    }
   ]
  },
  {
   "title": "AI Percent Match ",
   "type": "table",
   "gridPos": { "h": 19, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "Select \r\nUnix_timestamp(DateDTS) as \"time\"\r\n,Object\r\n,sum(case when EventType='Object found' then 1 else 0 end)/sum(case when EventType='Motion' then 1 else 0 end) as \"Percent Found\"\r\n,sum(case when EventType='Motion' then 1 else 0 end) as \"Total Events\"\r\nFROM BlueIrisMetrics\r\nWHERE $__timeFilter(DateDTS)\r\nAND \r\nEventType in ('Motion','Cancelled','Object found')\r\nGROUP BY Object\r\nOrder by DateDTS\r\n"
    }
   ]
  },
  {
   "title": "AI Process Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "Select \r\nunix_timestamp(DateDTS) as \"time\"\r\n,case when EventType='Cancelled' then ProcessTimeMS/1000 end as \"Cancelled\"\r\n,case when EventType='Object found' then ProcessTimeMS/1000 end as \"Object Found\"\r\n\r\nFROM BlueIrisMetrics\r\nWHERE $__timeFilter(DateDTS)"
    }
   ]
  },
  {
   "title": "AI Percent Match ",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 15 },
   "targets": [
    {
     "rawSql": "Select \r\nunix_timestamp(DateDTS) as \"time\"\r\n,Object\r\n,PercentMatch as \"\"\r\n\r\nFROM BlueIrisMetrics\r\nWHERE $__timeFilter(DateDTS)\r\nAND \r\nEventType='Object found'\r\nOrder by DateDTS\r\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  unix_timestamp(created) AS \"time\",\r\n  cast(StatNBR as decimal(18,2)) as 'CPU'\r\nFROM DeviceMonitoring\r\nWHERE\r\n  $__timeFilter(created)\r\n  and\r\n  DeviceNM='Blue Iris'\r\n  and\r\n  StatNM='CPU'\r\nORDER BY created"
    }
   ]
  }
 ]
}